# Use official PostgreSQL image
FROM postgres:latest

# Set environment variables (modify as needed)
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin
ENV POSTGRES_DB=jupyterlabdb

# Expose PostgreSQL port
EXPOSE 5432

# Default command to run PostgreSQL
CMD ["postgres"]
