apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  selector:
    app: postgresql
#  type: NodePort
  ports:
    - protocol: TCP
      port: 5432         # Internal Cluster Port
      targetPort: 5432   # Container Port
#      nodePort: 30432   # Exposed Port on the Node (30000-32767)
