apiVersion: v1
kind: Service
metadata:
  name: jupyterlab-service
spec:
  selector:
    app: jupyterlab
  type: NodePort
  ports:
    - protocol: TCP
      port: 8888         # Internal Cluster Port
      targetPort: 8888   # Container Port
      nodePort: 30088    # Exposed Port on the Node (30000-32767)
