apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32222   # Exposed Port on the Node (30000-32767)      
  type: NodePort  # Internal cluster access only
